services:
  jupyter-notebook:
    container_name: jupyter-notebook
    build: .
    ports:
      - "8888:8888"
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    environment:
      JUPYTER_ENABLE_LAB: yes
    volumes:
      - ./:/app
